config/routes.rb
Www::Application.routes.draw do

  resources :preorders

  get "sessions/new"

  resources :instances
  resources :pairs
  resources :sheets
  resources :topics
  resources :teams
  resources :users do
    member do
      get 'confirm'
      put 'verify'
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]

  
  match '/register' => 'users#new'
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/confirm' => 'users#confirm'
  match '/teaser' => 'preorders#new'
  match '/thanks' => 'preorders#index'
  match '/play' => 'play#index'
  
  get "home/index"
  
  root :to => "home#index"

end

app/models/pair.rb
class Pair < ActiveRecord::Base
  belongs_to :sheet
  validates :question, :presence => true
  validates :answer, :presence => true
  validates :sheet_id, :presence => true
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  # GET /pairs
  # GET /pairs.json
  def index
    @pairs = Pair.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pairs }
    end
  end

  # GET /pairs/1
  # GET /pairs/1.json
  def show
    @pair = Pair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pair }
    end
  end

  # GET /pairs/new
  # GET /pairs/new.json
  def new
    @pair = Pair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pair }
    end
  end

  # GET /pairs/1/edit
  def edit
    @pair = Pair.find(params[:id])
  end

  # POST /pairs
  # POST /pairs.json
  def create
    @pair = Pair.new(params[:pair])

    respond_to do |format|
      if @pair.save
        format.html { redirect_to @pair, notice: 'Pair was successfully created.' }
        format.json { render json: @pair, status: :created, location: @pair }
      else
        format.html { render action: "new" }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pairs/1
  # PUT /pairs/1.json
  def update
    @pair = Pair.find(params[:id])

    respond_to do |format|
      if @pair.update_attributes(params[:pair])
        format.html { redirect_to @pair, notice: 'Pair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pairs/1
  # DELETE /pairs/1.json
  def destroy
    @pair = Pair.find(params[:id])
    @pair.destroy

    respond_to do |format|
      format.html { redirect_to pairs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/views/pairs/_form.html.erb
<%= form_for(@pair) do |f| %>
  <% if @pair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pair.errors.count, "error") %> prohibited this pair from being saved:</h2>

      <ul>
      <% @pair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :choice_a %><br />
    <%= f.text_field :choice_a %>
  </div>
  <div class="field">
    <%= f.label :choice_b %><br />
    <%= f.text_field :choice_b %>
  </div>
  <div class="field">
    <%= f.label :choice_c %><br />
    <%= f.text_field :choice_c %>
  </div>
  <div class="field">
    <%= f.label :choice_d %><br />
    <%= f.text_field :choice_d %>
  </div>
  <div class="field">
    <%= f.label :sheet_id %><br />
    <%= f.number_field :sheet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pairs/edit.html.erb
<h1>Editing pair</h1>

<%= render 'form' %>

<%= link_to 'Show', @pair %> |
<%= link_to 'Back', pairs_path %>

app/views/pairs/index.html.erb
<h1>Listing pairs</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Answer</th>
    <th>Choice a</th>
    <th>Choice b</th>
    <th>Choice c</th>
    <th>Choice d</th>
    <th>Sheet</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pairs.each do |pair| %>
  <tr>
    <td><%= pair.question %></td>
    <td><%= pair.answer %></td>
    <td><%= pair.choice_a %></td>
    <td><%= pair.choice_b %></td>
    <td><%= pair.choice_c %></td>
    <td><%= pair.choice_d %></td>
    <td><%= pair.sheet_id %></td>
    <td><%= link_to 'Show', pair %></td>
    <td><%= link_to 'Edit', edit_pair_path(pair) %></td>
    <td><%= link_to 'Destroy', pair, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pair', new_pair_path %>

app/views/pairs/new.html.erb
<h1>New pair</h1>

<%= render 'form' %>

<%= link_to 'Back', pairs_path %>

app/views/pairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @pair.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @pair.answer %>
</p>

<p>
  <b>Choice a:</b>
  <%= @pair.choice_a %>
</p>

<p>
  <b>Choice b:</b>
  <%= @pair.choice_b %>
</p>

<p>
  <b>Choice c:</b>
  <%= @pair.choice_c %>
</p>

<p>
  <b>Choice d:</b>
  <%= @pair.choice_d %>
</p>

<p>
  <b>Sheet:</b>
  <%= @pair.sheet_id %>
</p>


<%= link_to 'Edit', edit_pair_path(@pair) %> |
<%= link_to 'Back', pairs_path %>