config/routes.rb
Www::Application.routes.draw do

  resources :preorders

  get "sessions/new"

  resources :instances
  resources :pairs
  resources :sheets
  resources :topics
  resources :teams
  resources :users do
    member do
      get 'confirm'
      put 'verify'
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]

  
  match '/register' => 'users#new'
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/confirm' => 'users#confirm'
  match '/teaser' => 'preorders#new'
  match '/thanks' => 'preorders#index'
  match '/play' => 'play#index'
  
  get "home/index"
  
  root :to => "home#index"

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :pairs
  validates :name, :presence => true
  validates :topic_id, :presence => true
  validates :user_id, :presence => true
  validates_associated :pairs
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  # GET /sheets
  # GET /sheets.json
  def index
    @sheets = Sheet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sheets }
    end
  end

  # GET /sheets/1
  # GET /sheets/1.json
  def show
    @sheet = Sheet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sheet }
    end
  end

  # GET /sheets/new
  # GET /sheets/new.json
  def new
    @sheet = Sheet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sheet }
    end
  end

  # GET /sheets/1/edit
  def edit
    @sheet = Sheet.find(params[:id])
  end

  # POST /sheets
  # POST /sheets.json
  def create
    @sheet = Sheet.new(params[:sheet])

    respond_to do |format|
      if @sheet.save
        format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
        format.json { render json: @sheet, status: :created, location: @sheet }
      else
        format.html { render action: "new" }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sheets/1
  # PUT /sheets/1.json
  def update
    @sheet = Sheet.find(params[:id])

    respond_to do |format|
      if @sheet.update_attributes(params[:sheet])
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheets/1
  # DELETE /sheets/1.json
  def destroy
    @sheet = Sheet.find(params[:id])
    @sheet.destroy

    respond_to do |format|
      format.html { redirect_to sheets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_form.html.erb
<%= form_for(@sheet) do |f| %>
  <% if @sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

      <ul>
      <% @sheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.number_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheets/edit.html.erb
<h1>Editing sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<h1>Listing sheets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Creator</th>
    <th>Topic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sheets.each do |sheet| %>
  <tr>
    <td><%= sheet.name %></td>
    <td><%= sheet.user_id %></td>
    <td><%= sheet.topic_id %></td>
    <td><%= link_to 'Show', sheet %></td>
    <td><%= link_to 'Edit', edit_sheet_path(sheet) %></td>
    <td><%= link_to 'Destroy', sheet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sheet', new_sheet_path %>

app/views/sheets/new.html.erb
<h1>New sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sheet.name %>
</p>

<p>
  <b>Creator:</b>
  <%= @sheet.user_id %>
</p>

<p>
  <b>Topic:</b>
  <%= @sheet.topic_id %>
</p>


<%= link_to 'Edit', edit_sheet_path(@sheet) %> |
<%= link_to 'Back', sheets_path %>