config/routes.rb
Www::Application.routes.draw do

  resources :preorders

  get "sessions/new"

  resources :instances
  resources :pairs
  resources :sheets
  resources :topics
  resources :teams
  resources :users do
    member do
      get 'confirm'
      put 'verify'
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]

  
  match '/register' => 'users#new'
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/confirm' => 'users#confirm'
  match '/teaser' => 'preorders#new'
  match '/thanks' => 'preorders#index'
  match '/play' => 'play#index'
  
  get "home/index"
  
  root :to => "home#index"

end

app/models/user.rb
require 'digest'
require 'securerandom'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :sheets
  has_one :team
  validates_associated :sheets 
  validates :email, :presence => true, 
                    :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :message => "The e-mail address is invalid." },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 },
                       :on           => :update
  # uncomment this line when the form has a tos
  # validates :terms_of_service, :acceptance => true
  before_save :encrypt_password, :generate_code #if password_required?
  after_create :registration_notification
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def self.confirm(email, submitted_code)
    user = find_by_email(email)
    if user.confirm_code == submitted_code && !user.nil?
      #user.confirmed = true
      #user.save(:validate => false)
      return user
    else
      return nil
    end
  end




  private

    def encrypt_password 
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

    def generate_code
      self.confirm_code = SecureRandom.hex(13)
    end
    
    def registration_notification
      UserMailer.registration_confirmation(self).deliver
    end

    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate, :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  respond_to :html, :json, :xml

  def index
    @users = User.all

    respond_with @users
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name

    respond_with @user
  end

  def new
    @user = User.new
    @title = "Register"

    respond_with @user
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit"

    respond_with @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { 
          redirect_to root_path, :notice => "An email has been sent to confirm your account." 
        }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        @title = "Register"
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      flash[:notice] = 'Profile updated.'
    end

    respond_with @user
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User destroyed."
  
    respond_with @user
  end

  # CONFIRM /users/dsaj3i12i123
  def confirm
    @user = User.confirm(params[:email], params[:confirm_code])
    
    if @user
      respond_to do |format|
        format.html { 
          flash[:notice] = 'Almost there! Just complete your profile to finish confirming.' 
        }
        format.json { head :no_content }
      end
    else
      redirect_to login_path, :error => "The confirmation code was incorrect."
    end
   
  end

  def verify
    @user = User.find(params[:id])
    sign_out

    respond_to do |format|
      if @user.update_attributes(params[:user])
        @user.confirmed = true
        @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'Profile updated.' }
        format.json { head :no_content }
      else
        @title = "Edit"
        format.html { render action: "confirm" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  private

    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end


end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

  def form_div(label, field)
    content_tag :div, :class => "control-group" do
      raw(label + content_tag(:div, field, :class => "controls"))
    end
  end


end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <%= form_div(f.label(:email, :class => "control-label"), f.text_field(:email)) %>
  <div class="form-actions">
    <%= f.submit "Register", :class => "btn btn-primary" %>
    <%= link_to "Back", users_path, :class => "btn" %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<h1>Confirm your account.</h1>

<div class="row">
  <div class="span4 offset4">
    <%= form_for @user, :as => :user, :url => verify_user_path(@user), :method => :put, :html => {:class => "form-horizontal"}  do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>

      <%= form_div(f.label(:name, :class => "control-label"), f.text_field(:name)) %>

      <%= form_div(f.label(:email, :class => "control-label"), f.text_field(:email)) %>

      <%= form_div(f.label(:password, :class => "control-label"), f.password_field(:password)) %>

      <%= form_div(f.label(:password_confirmation, :class => "control-label"), f.password_field(:password_confirmation)) %>

      <div class="form-actions">
        <%= f.submit "Confirm", :class => "btn btn-success" %>
      </div>

    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="span4 offset4">
    <h1>Update your profile</h1>
    <%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>

      <%= form_div(f.label(:name, :class => "control-label"), f.text_field(:name)) %>

      <%= form_div(f.label(:email, :class => "control-label"), f.text_field(:email)) %>

      <%= form_div(f.label(:password, :class => "control-label"), f.password_field(:password)) %>

      <%= form_div(f.label(:password_confirmation, :class => "control-label"), f.password_field(:password_confirmation)) %>

      <div class="form-actions">
        <%= f.submit "Save", :class => "btn btn-primary" %>
        <%= link_to "Back", @user, :class => "btn" %>
      </div>

    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Nick</th>
    <th>Answers r</th>
    <th>Answers w</th>
    <th>Wins</th>
    <th>Losses</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.nick %></td>
    <td><%= user.answers_r %></td>
    <td><%= user.answers_w %></td>
    <td><%= user.wins %></td>
    <td><%= user.losses %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% if signed_in? && current_user.admin? %>
      <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<fieldset>
  <legend>New user</legend>

<%= render 'form' %>
</fieldset>

app/views/users/show.html.erb
<div class="span12">
  <div class="hero-unit">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </div>
</div>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Nick:</b>
  <%= @user.nick %>
</p>

<p>
  <b>Answers r:</b>
  <%= @user.answers_r %>
</p>

<p>
  <b>Answers w:</b>
  <%= @user.answers_w %>
</p>

<p>
  <b>Wins:</b>
  <%= @user.wins %>
</p>

<p>
  <b>Losses:</b>
  <%= @user.losses %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>